/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AppConvoyRouteImport } from './routes/_app.convoy'
import { Route as AppEcomoovRouteImport } from './routes/_app.ecomoov'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppNavigateRouteImport } from './routes/_app.navigate'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppTripsRouteImport } from './routes/_app.trips'
import { Route as OauthAuthorizeRouteImport } from './routes/oauth.authorize'
import { Route as OauthConsentRouteImport } from './routes/oauth.consent'
import { Route as OauthTokenRouteImport } from './routes/oauth.token'
import { Route as DotlovableOauthAuthorizeRouteImport } from './routes/[.]lovable.oauth.authorize'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiMapCategoryRouteImport } from './routes/api/map/category'
import { Route as ApiMapDetailsRouteImport } from './routes/api/map/details'
import { Route as ApiMapDirectionsRouteImport } from './routes/api/map/directions'
import { Route as ApiMapIsochroneRouteImport } from './routes/api/map/isochrone'
import { Route as ApiMapReverseRouteImport } from './routes/api/map/reverse'
import { Route as ApiMapSearchRouteImport } from './routes/api/map/search'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppConvoyRoute = AppConvoyRouteImport.update({
  id: '/convoy',
  path: '/convoy',
  getParentRoute: () => AppRoute,
} as any)
const AppEcomoovRoute = AppEcomoovRouteImport.update({
  id: '/ecomoov',
  path: '/ecomoov',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppNavigateRoute = AppNavigateRouteImport.update({
  id: '/navigate',
  path: '/navigate',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTripsRoute = AppTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AppRoute,
} as any)
const OauthAuthorizeRoute = OauthAuthorizeRouteImport.update({
  id: '/oauth/authorize',
  path: '/oauth/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthTokenRoute = OauthTokenRouteImport.update({
  id: '/oauth/token',
  path: '/oauth/token',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthAuthorizeRoute =
  DotlovableOauthAuthorizeRouteImport.update({
    id: '/.lovable/oauth/authorize',
    path: '/.lovable/oauth/authorize',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMapCategoryRoute = ApiMapCategoryRouteImport.update({
  id: '/api/map/category',
  path: '/api/map/category',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMapDetailsRoute = ApiMapDetailsRouteImport.update({
  id: '/api/map/details',
  path: '/api/map/details',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMapDirectionsRoute = ApiMapDirectionsRouteImport.update({
  id: '/api/map/directions',
  path: '/api/map/directions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMapIsochroneRoute = ApiMapIsochroneRouteImport.update({
  id: '/api/map/isochrone',
  path: '/api/map/isochrone',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMapReverseRoute = ApiMapReverseRouteImport.update({
  id: '/api/map/reverse',
  path: '/api/map/reverse',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMapSearchRoute = ApiMapSearchRouteImport.update({
  id: '/api/map/search',
  path: '/api/map/search',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/convoy': typeof AppConvoyRoute
  '/ecomoov': typeof AppEcomoovRoute
  '/home': typeof AppHomeRoute
  '/navigate': typeof AppNavigateRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/trips': typeof AppTripsRoute
  '/oauth/authorize': typeof OauthAuthorizeRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/oauth/token': typeof OauthTokenRoute
  '/.lovable/oauth/authorize': typeof DotlovableOauthAuthorizeRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/map/category': typeof ApiMapCategoryRoute
  '/api/map/details': typeof ApiMapDetailsRoute
  '/api/map/directions': typeof ApiMapDirectionsRoute
  '/api/map/isochrone': typeof ApiMapIsochroneRoute
  '/api/map/reverse': typeof ApiMapReverseRoute
  '/api/map/search': typeof ApiMapSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/convoy': typeof AppConvoyRoute
  '/ecomoov': typeof AppEcomoovRoute
  '/home': typeof AppHomeRoute
  '/navigate': typeof AppNavigateRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/trips': typeof AppTripsRoute
  '/oauth/authorize': typeof OauthAuthorizeRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/oauth/token': typeof OauthTokenRoute
  '/.lovable/oauth/authorize': typeof DotlovableOauthAuthorizeRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/map/category': typeof ApiMapCategoryRoute
  '/api/map/details': typeof ApiMapDetailsRoute
  '/api/map/directions': typeof ApiMapDirectionsRoute
  '/api/map/isochrone': typeof ApiMapIsochroneRoute
  '/api/map/reverse': typeof ApiMapReverseRoute
  '/api/map/search': typeof ApiMapSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_app/convoy': typeof AppConvoyRoute
  '/_app/ecomoov': typeof AppEcomoovRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/navigate': typeof AppNavigateRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/trips': typeof AppTripsRoute
  '/oauth/authorize': typeof OauthAuthorizeRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/oauth/token': typeof OauthTokenRoute
  '/.lovable/oauth/authorize': typeof DotlovableOauthAuthorizeRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/map/category': typeof ApiMapCategoryRoute
  '/api/map/details': typeof ApiMapDetailsRoute
  '/api/map/directions': typeof ApiMapDirectionsRoute
  '/api/map/isochrone': typeof ApiMapIsochroneRoute
  '/api/map/reverse': typeof ApiMapReverseRoute
  '/api/map/search': typeof ApiMapSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/privacy-policy'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/convoy'
    | '/ecomoov'
    | '/home'
    | '/navigate'
    | '/profile'
    | '/settings'
    | '/trips'
    | '/oauth/authorize'
    | '/oauth/consent'
    | '/oauth/token'
    | '/.lovable/oauth/authorize'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/map/category'
    | '/api/map/details'
    | '/api/map/directions'
    | '/api/map/isochrone'
    | '/api/map/reverse'
    | '/api/map/search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/privacy-policy'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/convoy'
    | '/ecomoov'
    | '/home'
    | '/navigate'
    | '/profile'
    | '/settings'
    | '/trips'
    | '/oauth/authorize'
    | '/oauth/consent'
    | '/oauth/token'
    | '/.lovable/oauth/authorize'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/map/category'
    | '/api/map/details'
    | '/api/map/directions'
    | '/api/map/isochrone'
    | '/api/map/reverse'
    | '/api/map/search'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/mcp'
    | '/privacy-policy'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_app/convoy'
    | '/_app/ecomoov'
    | '/_app/home'
    | '/_app/navigate'
    | '/_app/profile'
    | '/_app/settings'
    | '/_app/trips'
    | '/oauth/authorize'
    | '/oauth/consent'
    | '/oauth/token'
    | '/.lovable/oauth/authorize'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/map/category'
    | '/api/map/details'
    | '/api/map/directions'
    | '/api/map/isochrone'
    | '/api/map/reverse'
    | '/api/map/search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  OauthAuthorizeRoute: typeof OauthAuthorizeRoute
  OauthConsentRoute: typeof OauthConsentRoute
  OauthTokenRoute: typeof OauthTokenRoute
  DotlovableOauthAuthorizeRoute: typeof DotlovableOauthAuthorizeRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiMapCategoryRoute: typeof ApiMapCategoryRoute
  ApiMapDetailsRoute: typeof ApiMapDetailsRoute
  ApiMapDirectionsRoute: typeof ApiMapDirectionsRoute
  ApiMapIsochroneRoute: typeof ApiMapIsochroneRoute
  ApiMapReverseRoute: typeof ApiMapReverseRoute
  ApiMapSearchRoute: typeof ApiMapSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/convoy': {
      id: '/_app/convoy'
      path: '/convoy'
      fullPath: '/convoy'
      preLoaderRoute: typeof AppConvoyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ecomoov': {
      id: '/_app/ecomoov'
      path: '/ecomoov'
      fullPath: '/ecomoov'
      preLoaderRoute: typeof AppEcomoovRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/navigate': {
      id: '/_app/navigate'
      path: '/navigate'
      fullPath: '/navigate'
      preLoaderRoute: typeof AppNavigateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trips': {
      id: '/_app/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof AppTripsRouteImport
      parentRoute: typeof AppRoute
    }
    '/oauth/authorize': {
      id: '/oauth/authorize'
      path: '/oauth/authorize'
      fullPath: '/oauth/authorize'
      preLoaderRoute: typeof OauthAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/token': {
      id: '/oauth/token'
      path: '/oauth/token'
      fullPath: '/oauth/token'
      preLoaderRoute: typeof OauthTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/authorize': {
      id: '/.lovable/oauth/authorize'
      path: '/.lovable/oauth/authorize'
      fullPath: '/.lovable/oauth/authorize'
      preLoaderRoute: typeof DotlovableOauthAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/map/category': {
      id: '/api/map/category'
      path: '/api/map/category'
      fullPath: '/api/map/category'
      preLoaderRoute: typeof ApiMapCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/map/details': {
      id: '/api/map/details'
      path: '/api/map/details'
      fullPath: '/api/map/details'
      preLoaderRoute: typeof ApiMapDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/map/directions': {
      id: '/api/map/directions'
      path: '/api/map/directions'
      fullPath: '/api/map/directions'
      preLoaderRoute: typeof ApiMapDirectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/map/isochrone': {
      id: '/api/map/isochrone'
      path: '/api/map/isochrone'
      fullPath: '/api/map/isochrone'
      preLoaderRoute: typeof ApiMapIsochroneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/map/reverse': {
      id: '/api/map/reverse'
      path: '/api/map/reverse'
      fullPath: '/api/map/reverse'
      preLoaderRoute: typeof ApiMapReverseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/map/search': {
      id: '/api/map/search'
      path: '/api/map/search'
      fullPath: '/api/map/search'
      preLoaderRoute: typeof ApiMapSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppConvoyRoute: typeof AppConvoyRoute
  AppEcomoovRoute: typeof AppEcomoovRoute
  AppHomeRoute: typeof AppHomeRoute
  AppNavigateRoute: typeof AppNavigateRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTripsRoute: typeof AppTripsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConvoyRoute: AppConvoyRoute,
  AppEcomoovRoute: AppEcomoovRoute,
  AppHomeRoute: AppHomeRoute,
  AppNavigateRoute: AppNavigateRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTripsRoute: AppTripsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  OauthAuthorizeRoute: OauthAuthorizeRoute,
  OauthConsentRoute: OauthConsentRoute,
  OauthTokenRoute: OauthTokenRoute,
  DotlovableOauthAuthorizeRoute: DotlovableOauthAuthorizeRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiMapCategoryRoute: ApiMapCategoryRoute,
  ApiMapDetailsRoute: ApiMapDetailsRoute,
  ApiMapDirectionsRoute: ApiMapDirectionsRoute,
  ApiMapIsochroneRoute: ApiMapIsochroneRoute,
  ApiMapReverseRoute: ApiMapReverseRoute,
  ApiMapSearchRoute: ApiMapSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
